# Generated by Django 5.1.5 on 2025-02-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salarioOferta', models.IntegerField()),
                ('fechaPublicacion', models.DateTimeField()),
                ('disponibilidad', models.CharField(max_length=255)),
                ('experienciaOferta', models.CharField(max_length=255)),
                ('descripcionOferta', models.CharField(max_length=255)),
                ('modalidadOferta', models.CharField(max_length=255)),
                ('horLaboralOferta', models.CharField(max_length=255)),
                ('requisitosOferta', models.CharField(max_length=255)),
                ('seleccionOferta', models.CharField(max_length=255)),
                ('ubiOferta', models.CharField(max_length=255)),
                ('numeroEmpresa', models.CharField(max_length=255)),
                ('emailEmpresa', models.CharField(max_length=255)),
                ('tituloOferta', models.CharField(max_length=255)),
            ],
        ),
    ]
