# Generated by Django 5.1.6 on 2025-02-23 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('En progreso', 'En progreso'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=20, verbose_name='Estado')),
                ('tipo', models.CharField(choices=[('Soporte técnico', 'Soporte técnico'), ('Problema de cuenta', 'Problema de cuenta'), ('Reporte de error', 'Reporte de error'), ('General', 'General')], default='General', max_length=20, verbose_name='Tipo de ticket')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
