# Generated by Django 5.1.6 on 2025-02-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='habilidades',
        ),
        migrations.AddField(
            model_name='persona',
            name='cargo',
            field=models.CharField(choices=[('Desarrollador', 'Desarrollador'), ('Diseñador', 'Diseñador'), ('Analista', 'Analista'), ('Gerente', 'Gerente'), ('Otro', 'Otro')], default='Desarrollador', max_length=50, verbose_name='Cargo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.EmailField(default='ejemplo123@gmail.com', max_length=254, verbose_name='Correo Electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/', verbose_name='Foto de Perfil'),
        ),
        migrations.AddField(
            model_name='persona',
            name='perfil_laboral',
            field=models.TextField(default='desarrollar programas', verbose_name='Perfil Laboral'),
            preserve_default=False,
        ),
    ]
