# Generated by Django 5.1.6 on 2025-02-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_persona_habilidades_persona_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.EmailField(default='empresaejemplo1qgmail.com', max_length=254, verbose_name='Correo Electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_empresa/', verbose_name='Logo'),
        ),
    ]
