# Generated by Django 5.1.6 on 2025-02-22 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_empresa_email_empresa_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100, verbose_name='Nombre de la Empresa')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('en_progreso', models.BooleanField(default=False, verbose_name='En Progreso')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.persona', verbose_name='Persona')),
            ],
        ),
        migrations.CreateModel(
            name='FormacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_educativo', models.CharField(choices=[('Bachiller', 'Bachiller'), ('Técnico', 'Técnico'), ('Tecnólogo', 'Tecnólogo'), ('Pregrado', 'Pregrado'), ('Posgrado', 'Posgrado'), ('Curso', 'Curso'), ('Otro', 'Otro')], max_length=50, verbose_name='Nivel Educativo')),
                ('institucion', models.CharField(max_length=100, verbose_name='Institución')),
                ('titulo_obtenido', models.CharField(max_length=100, verbose_name='Título Obtenido')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('en_progreso', models.BooleanField(default=False, verbose_name='En Progreso')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.persona', verbose_name='Persona')),
            ],
        ),
    ]
