# Generated by Django 5.1.6 on 2025-02-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_experiencialaboral_formacionacademica'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ubicacion',
            field=models.CharField(default='Cali', max_length=100, verbose_name='Ubicación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='ubicacion',
            field=models.CharField(default='Cali', max_length=100, verbose_name='Ubicación'),
            preserve_default=False,
        ),
    ]
