# Generated by Django 5.1.6 on 2025-02-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_empresa_ubicacion_persona_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='nombre_completo',
            field=models.CharField(default='ejemplo', max_length=100, verbose_name='Nombre Completo'),
            preserve_default=False,
        ),
    ]
