# Generated by Django 5.1.7 on 2025-03-07 03:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_calificacionempresa_calificacionpersona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='cargo',
        ),
        migrations.AddField(
            model_name='persona',
            name='habilidades',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Habilidades'),
            preserve_default=False,
        ),
    ]
