# Generated by Django 5.1.6 on 2025-03-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_persona_cargo_persona_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='eslogan',
            field=models.CharField(blank=True, max_length=200, verbose_name='Eslogan'),
        ),
        migrations.AddField(
            model_name='persona',
            name='profesion',
            field=models.CharField(default='software', max_length=100, verbose_name='Profesión'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(max_length=200, verbose_name='Dirección'),
        ),
    ]
