# Generated by Django 5.1.6 on 2025-02-22 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_remove_persona_habilidades_persona_cargo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario')),
                ('fecha_publicacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Publicación')),
                ('fecha_cierre', models.DateField(verbose_name='Fecha de Cierre')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa', verbose_name='Empresa')),
            ],
        ),
    ]
