# Generated by Django 5.1.6 on 2025-02-22 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
        ('usuarios', '0002_remove_persona_habilidades_persona_cargo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Postulación')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20, verbose_name='Estado')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofertas.oferta', verbose_name='Oferta')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.persona', verbose_name='Trabajador')),
            ],
        ),
    ]
