# Generated by Django 5.1.6 on 2025-02-22 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_postulacion'),
        ('usuarios', '0002_remove_persona_habilidades_persona_cargo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Puntuación')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('fecha_calificacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Calificación')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa', verbose_name='Empresa')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.persona', verbose_name='Trabajador')),
            ],
        ),
    ]
