# Generated by Django 5.1.6 on 2025-02-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0004_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='ubicacion',
            field=models.CharField(default='Cali', max_length=100, verbose_name='Ubicación'),
            preserve_default=False,
        ),
    ]
