# Generated by Django 5.1.6 on 2025-02-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0006_alter_ticket_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='fecha_contratacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Contratación'),
        ),
    ]
