# Generated by Django 5.1.5 on 2025-02-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitEmpresa', models.CharField(max_length=255)),
                ('nombreEmpresa', models.CharField(max_length=255)),
                ('perfilEmpresa', models.CharField(max_length=450)),
                ('logoEmpresa', models.BinaryField()),
                ('emailEmpresa', models.CharField(max_length=255)),
                ('numeroEmpresa', models.CharField(max_length=255)),
                ('codEmpresa', models.CharField(max_length=255)),
            ],
        ),
    ]
